<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$demo = $this->asset('demo');

/*            <!--ul class="nav child_menu">
              <li><a href="form.html">General Form</a></li>
              <li><a href="form_advanced.html">Advanced Components</a></li>
              <li><a href="form_validation.html">Form Validation</a></li>
              <li><a href="form_wizards.html">Form Wizard</a></li>
              <li><a href="form_upload.html">Form Upload</a></li>
              <li><a href="form_buttons.html">Form Buttons</a></li>
          </ul-->
*/
?>

<div class="menu_section">
    <ul class="nav side-menu">
        <li id="home"><a href="/"><i class="fa fa-dashboard"></i> Dashboard<span class="fa"></span></a>
        </li>
        <li><a href="<?= $this->url('ebay', ['action' => 'index']) ?>"><i class="fa fa-th-list"></i> Ebay product search<span
                        class="fa"></span></a>
        </li>
    </ul>
</div>
