#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');


use yii\db\Connection;

$config = require __DIR__ . '/config/console.php';

/**
 * config has some required data related to the console commands
 * here is the migration guide https://p0vidl0.info/yii2-api-guides/guide-ru-db-migrations.html
 * TODO it is good to use custom migration template files.
 * 'controllerMap' => [
        'migrate' => [
            'class' => 'yii\console\controllers\MigrateController',
            'migrationNamespaces' => [
                'app\migrations',
                'some\extension\migrations',
            ],
            //'migrationPath' => null, // allows to disable not namespaced migration completely
        ],
    ],

 */

require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$dbParamsLocal = $config['db'];
$dbParamsLocal['class'] = Connection::class;
//$dbParamsLocal['charset'] = 'utf8';

unset($dbParamsLocal['driver'], $dbParamsLocal['driver_options']);

$appConfig = [
    'id' => 'scraper-console',
    'basePath' => __DIR__ . '/vendor/yiisoft/yii2/console',
    'controllerNamespace' => 'yii\console\controllers',
    'components' => [
        'db' => $dbParamsLocal,
    ],
];
if (isset($config['controllerMap'])) {
    $appConfig['controllerMap'] = $config['controllerMap'];
}

$vendorPath = dirname(__DIR__ . '/../vendor/');
/**
 *
 */
$application = new yii\console\Application($appConfig);
if ($vendorPath !== null) {
    $application->setVendorPath($vendorPath);
}
$exitCode = $application->run();
exit($exitCode);