<p>Школа – один из лучших периодов в жизни. Иногда друзья, ты которых находишь в школе, остаются с тобой на всю
    жизнь...</p>
<p>И мы стараемся сделать школьные годы интересными и запоминающимися, ведь они никогда не повторятся!</p>

<!-- -->
<div class="container-fluid">
    <div class="row row-flex row-flex-wrap">
        <div class="w100">
            <div class="wel" style="background-image:url(/wp-content/uploads/section/club.jpg);">
                <div class="dark-bg" data="dark-bg" id="dark-bg">
                    <div>
                        <div class="tag">Газета</div>
                        <h3>ШОК-Ю</h3>
                        <p>Каждую четверть выходит «ШОК-Ю» - настоящая газета, которая создаётся по всем правилам
                            журналистики – от сбора и написания материалов до оформления. Газета освещает все аспекты
                            жизни школы, имеет собственных корреспондентов и специальное приложение «Известия
                            Парламента». Ученики, работающие в газете, также готовят материалы для школьного ТВ и нашего
                            сайта.</p>
                        <p><a href="/category/shock-u/" class="event_click">Подробнее</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- -->
<div class="container-fluid">
    <div class="row row-flex row-flex-wrap">
        <div class="col-sm-4">
            <div class="wel" style="background-color: #c2ff00">
                <div class="dark-bg" data="dark-bg">
                    <div>
                        <div class="tag">Самоуправление</div>
                        <h3>Парламент</h3>
                        <p>Школьный Парламент (дискуссионный клуб) – это реальный орган школьного самоуправления.
                            Выборов депутатов проходят каждый год, в строгом соответствии о школьным Законом «О
                            Парламенте».</p>
                        <p>Парламент рассматривает вопросы самоуправления в школе, дисциплины учеников, конфликтные
                            ситуации, а также принимает законы по различным вопросам внутренней жизни школы.</p>
                        <p>Депутат Парламента «Юнион» - это, прежде всего, дисциплина и ответственность: за каждым стоит
                            реальное дело.</p>
                        <p><a href="/category/shock-u/parliament/" class="event_click">Подробнее</a></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="wel" style="background-image:url(/wp-content/uploads/section/pangea.jpg);">
                <div class="dark-bg" data="dark-bg">
                    <div>
                        <div class="tag">Мега-игра</div>
                        <h3>Вселенная Пангея</h3>
                        <p>«Пангея» - уникальный авторский проект, дающий метапредметные навыки. Школьники придумали
                            некую планету, похожую на Землю, распределили между собой материки и государства,
                            разработали свои собственные географические названия. В своих государствах они добывают
                            полезные ископаемые и выращивают сельскохозяйственные продукты, строят заводы и фабрики,
                            школы и больницы, порты и железные дороги… </p>
                        <p>В ходе проекта ученики составляют доходные и расходные бюджеты своих стран, учатся
                            планировать, решать политические конфликты путем переговоров. Для работы с бюджетами они
                            осваивают Microsoft Excel, для работы с картами – графические редакторы. Проект даёт базу
                            для уроков экономической географии в последующих 10-11 классах, обобщает и актуализирует
                            материал из курса обществознания по экономике, социологии и политологии.<br>Aвтор: Игорь
                            Резун</p>
                        <p><a href="/category/shock-u/pangea/" class="event_click">Подробнее</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- -->
<div class="container-fluid">
    <div class="row row-flex row-flex-wrap">
        <div class="w100">
            <div class="wel" style="background-image:url(/wp-content/uploads/section/millions.jpg);">
                <div class="dark-bg" data="dark-bg">
                    <div>
                        <div class="tag">Мега-игра</div>
                        <h3>50 миллионов</h3>
                        <p>Экономическая обучающая игра построена на принципе «Монополии», однако, по сравнению с ней,
                            усложнена и имеет несколько уровней. В игру введены несколько видов конвертируемых валют с
                            возможностью обмена, коммерческие и другие банки, осуществляется выпуск акций и выдача
                            векселей… Игра развивается по определённому сценарию, предусматривающему биржевые колебания
                            и кризисы, поэтому игроки не просто зарабатывают большие капиталы - они учатся распоряжаться
                            ими, инвестировать, выбирать тактику финансовой игры на бирже. Проект даёт знания,
                            необходимые в реальной жизни – по управлению семейным бюджетом, пользованию кредитами и игры
                            на Интернет-биржах ценных бумаг.<br>Aвтор: Игорь Резун</p>
                        <p><a href="/category/shock-u/millions/" class="event_click">Подробнее</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- -->

<!-- -->
<div class="container-fluid">
    <div class="row row-flex row-flex-wrap">
        <div class="col-sm-4">
            <div class="wel" style="background-image:url(/wp-content/uploads/section/congratulations.jpg);">
                <div class="dark-bg" data="dark-bg">
                    <div>
                        <div class="tag">Наши люди</div>
                        <h3>Любим, ценим, поздравляем!</h3>
                        <p></p>
                        <p>"Юнион" - большая семья. Творческие, талантливые, целеустремленные!</p>
                        <p><a href="/category/congratulations/" class="event_click">Подробнее</a></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="wel" style="background-color: #c2ff00">
                <div class="dark-bg" data="dark-bg">
                    <div>
                        <div class="tag">К нам приходят</div>
                        <h3>Наши гости</h3>
                        <p>В гостях у «Юнион» представители редких профессий, коллекционеры, общественные деятели,
                            авторы удивительных проектов, спортсмены, художники… Словом, интересные люди!</p>
                        <p><a href="/category/guests/" class="event_click">Подробнее</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type='text/javascript'>
    jQuery(".event_click").mouseover(function () {
        element = jQuery(this);
        element.closest('div[data^="dark-bg"]').addClass('dark-bg-over').removeClass('dark-bg');
    });
    jQuery(".event_click").mouseout(function () {
        element = jQuery(this);
        element.closest('div[data^="dark-bg"]').addClass('dark-bg').removeClass('dark-bg-over');
    });
</script>
