<div class="dashboard_graph">
    <div class="row x_title">
        <div class="col-md-6">
            <h3>Network Activities
                <small>Graph title sub-title</small>
            </h3>
        </div>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div id="<?= $this->chartId ?>" class="demo-placeholder"></div>
    </div>
    <div class="clearfix"></div>
</div>

<script>
    <?php
    $lines1 = [];
    $lines2 = [];
    $lines3 = [];
    $i = 0;
    foreach ($this->data as $key => $value) {
        if ($value['sync']) {
            $line = "['" . $value['timestamp'] . "'," . $value['sync'] . "]";
            $lines1[] = $line;
            $line = "['" . $value['timestamp'] . "'," . $value['price'] . "]";
            $lines2[] = $line;
            $line = "['" . $value['timestamp'] . "'," . $value['stock'] . "]";
            $lines3[] = $line;
        }
    }
    ?>

    var <?= $this->chartId ?>_data1 = [
        <?php  echo implode(",\n", $lines1) ?>
    ];
    var <?= $this->chartId ?>_data2 = [
        <?php echo implode(",\n", $lines2) ?>
    ];
    var <?= $this->chartId ?>_data3 = [
        <?php echo implode(",\n", $lines3) ?>
    ];
    var <?= $this->chartId ?>_settings = {
        series: {
            lines: {
                show: false,
                fill: true
            },
            splines: {
                show: true,
                tension: 0.4,
                lineWidth: 1,
                fill: 0.4
            },
            points: {
                radius: 0,
                show: true
            },
            shadowSize: 2
        },
        grid: {
            verticalLines: true,
            hoverable: true,
            clickable: true,
            tickColor: "#e5e5e5",
            borderWidth: 1,
            color: '#fff'
        },
        colors: ["rgba(38, 185, 154, 0.38)", "rgba(3, 88, 106, 0.38)", "rgba(3, 88, 40, 0.38)"],
        xaxis: {
            tickColor: "rgba(51, 51, 51, 0.06)",
            mode: "time",
            tickSize: [1, "hour"],
            tickLength: 10,
            axisLabel: "Date",
            axisLabelUseCanvas: true,
            axisLabelFontSizePixels: 10,
            axisLabelFontFamily: 'myriad-pro, myriad-pro-n2, Arial, Helvetica, sans-serif',
            axisLabelPadding: 10
        },
        yaxis: {
            ticks: 8,
            tickColor: "rgba(51, 51, 51, 0.06)",
        },
        tooltip: false
    };
    $(function () {
        if ($("#<?= $this->chartId ?>").length) {
            console.log(<?= $this->chartId ?>);
            $.plot($("#<?= $this->chartId ?>"), [<?= $this->chartId ?>_data1, <?= $this->chartId ?>_data2, <?= $this->chartId ?>_data3], <?= $this->chartId ?>_settings);
        }
    });

</script>