<div class="x_panel">
    <div class="x_title">
        <h2>Products synced per 24 hours</h2>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
        <canvas id="<?= $this->chartId ?>" style="width:100%; height:400px;"></canvas>
    </div>
</div>
<?php
$sync = [];
$price = [];
$stock = [];
$inStock = [];
$outOfStock = [];
$labels = [];
$i = 0;
foreach ($this->data as $key => $value) {
    if ($value['sync']) {
        $sync[] = $value['sync'];
        $price[] = $value['price'];
        $stock[] = $value['stock'];
        $inStock[] = $value['inStock'];
        $outOfStock[] = $value['outOfStock'];
        $labels[] = "'" . substr($key, -5) . "'";
    }
}
?>
<script>
    $(function () {
        if ($('#<?= $this->chartId ?>').length) {

            var ctx = document.getElementById("<?= $this->chartId ?>");
            ctx.height = 80;
            var lineChart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: [<?= implode(",", $labels) ?>],
                    datasets: [{
                        label: "Synced",
                        backgroundColor: "rgba(195, 209, 213, 0.31)",
                        borderColor: "rgba(195, 209, 213, 0.7)",
                        pointBorderColor: "rgba(195, 209, 213, 0.7)",
                        pointBackgroundColor: "rgba(195, 209, 213, 0.7)",
                        pointHoverBackgroundColor: "#fff",
                        pointHoverBorderColor: "rgba(220,220,220,1)",
                        pointBorderWidth: 1,
                        data: [<?= implode(",", $sync) ?>]
                    }, {
                        label: "Stock change",
                        backgroundColor: "rgba(22, 65, 85, 0.3)",
                        borderColor: "rgba(22, 65, 85, 0.70)",
                        pointBorderColor: "rgba(22, 65, 85, 0.70)",
                        pointBackgroundColor: "rgba(22, 65, 85, 0.70)",
                        pointHoverBackgroundColor: "#fff",
                        pointHoverBorderColor: "rgba(151,187,205,1)",
                        pointBorderWidth: 1,
                        data: [<?= implode(",", $stock) ?>]
                    }, {
                        label: "Price change",
                        backgroundColor: "rgba(2, 152, 219, 0)",
                        borderColor: "rgba(2, 152, 219, 0.70)",
                        pointBorderColor: "rgba(2, 152, 219, 0.70)",
                        pointBackgroundColor: "rgba(2, 152, 219, 0.70)",
                        pointHoverBackgroundColor: "#fff",
                        pointHoverBorderColor: "rgba(151,187,205,1)",
                        pointBorderWidth: 1,
                        data: [<?= implode(",", $price) ?>]
                    }, {
                        label: "Got In Stock",
                        backgroundColor: "rgba(33,185,23,0.0)",
                        borderColor: "rgba(33,185,23,0.49)",
                        pointBorderColor: "rgba(33,185,23,0.49)",
                        pointBackgroundColor: "rgba(33,185,23,0.49)",
                        pointHoverBackgroundColor: "#ffC",
                        pointHoverBorderColor: "rgba(151,187,205,1)",
                        pointBorderWidth: 0.5,
                        data: [<?= implode(",", $inStock) ?>]
                    }, {
                        label: "Got Out of Stock",
                        backgroundColor: "rgba(22, 65, 85, 0.0)",
                        borderColor: "rgba(255,11,5,0.84)",
                        pointBorderColor: "rgba(255,11,5,0.84)",
                        pointBackgroundColor: "rgba(255,11,5,0.84)",
                        pointHoverBackgroundColor: "#ffc",
                        pointHoverBorderColor: "rgba(22, 65, 85, 0.70)",
                        pointBorderWidth: 0.5,
                        data: [<?= implode(",", $outOfStock) ?>]
                    }]
                },
            });

        }
    });
</script>