<?php $gHelper = new Parser\Model\Helper\Helper(); ?>
<div class="">

    <div class="page-title">
        <div class="title_center">
            <h1>Manage Magento stores</h1>
        </div>
    </div>

</div>
<div class="clearfix"></div>
<p><a target="_blank" class="btn btn-default" href="<?= $this->url('magento', ['action' => 'showRequestsLog']) ?>">view request errors</a> <a target="_blank" class="btn btn-default" href="<?= $this->url('magento', ['action' => 'showLog']) ?>">view request log</a></p>
<div class="row">

    <table id="datatable-responsive" class="table table-striped jambo_table bulk_action dataTable magento"
           cellspacing="0"
           width="100%">
        <thead>
        <tr>
            <th>Enable</th>
            <th>Title</th>
            <th>Path</th>
            <th>Secret</th>
            <th>Settings</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php if (count($list)) : ?>
            <?php foreach ($list as $odd => $item) : ?>
                <tr role="row" class="<?php echo $odd % 2 ? "odd" : "even"; ?>">
                    <td><?= $gHelper::getColoredBoolean($item['enable']) ?></td>
                    <td><?= $item['title'] ?></td>
                    <td><?= $item['magento_trigger_path'] ?></td>
                    <td><?= $item['magento_trigger_key'] ?></td>
                    <td>
                        <ul class="to_do">
                            <li><span data-toggle="tooltip" data-placement="left"
                                      data-original-title="Send images data to Magento">Send Images</span> <?= $gHelper::getColoredBoolean($item['send_images']) ?>
                            </li>
                            <li><span data-toggle="tooltip" data-placement="left"
                                      data-original-title="Send a delete request if the product's sync status is not Active">Delete products</span> <?= $gHelper::getColoredBoolean($item['delete_trigger']) ?>
                            </li>
                            <li><span data-toggle="tooltip" data-placement="left"
                                      data-original-title="Send a create product request if the product is missing in the Magento store">Create products</span> <?= $gHelper::getColoredBoolean($item['create_trigger']) ?>
                            </li>
                            <li><span data-toggle="tooltip" data-placement="left"
                                      data-original-title="Check if a description is different between the Engine and the Magento store and send an update command if there is a difference">Check description</span> <?= $gHelper::getColoredBoolean($item['check_description']) ?>
                            </li>
                        </ul>
                    </td>
                    <td>
                        <a href="<?= $this->url('magento', ['action' => 'list']) . "?id=" . $item['parser_magento_id'] . "&mode=update#magento-form" ?>"
                           class="btn btn-default" title="Manual start of synchronization">
                            Edit </a><br/>
                        <a href="<?= $this->url('magento', ['action' => 'delete']) . "?id=" . $item['parser_magento_id'] ?>"
                           class="btn btn-default" title="Delete the item"> Delete </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php else : ?>
            <tr role="row" class="even">
                <td colspan="6">There are no Magento stores specified</td>
            </tr>
        <?php endif; ?>
        </tbody>
    </table>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">

                <div class="x_title">
                    <?php if ($update['parser_magento_id']) : ?>
                        <h1>Editing Magento store settings with
                            path <?= $update['magento_trigger_path'] ?></h1>
                    <?php else : ?>
                        <h1>Add new Magento store</h1>
                    <?php endif; ?>
                    <div class="clearfix"></div>
                </div>


                <div class="x_content">
                    <form id="magento-form" method="post"
                          action="<?= $this->url('magento', ['action' => 'list']) ?>"
                          class="form-horizontal form-label-left">

                        <input type="hidden" name="parser_magento_id"
                               value="<?= $update['parser_magento_id'] ?>"/>
                        <?php if ($this->message) : ?>
                            <div class="alert alert-info alert-dismissible" role="alert">
                                <strong><?= $this->message ?></strong>
                            </div>
                        <?php endif; ?>
                        <?php if ($this->errors) : ?>
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <strong><?= $this->errors ?></strong>
                            </div>
                        <?php endif; ?>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Title
                                <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input class="form-control" type="text" name="title"
                                       value="<?= $update['title'] ?>"/>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Enable

                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <div id="locale-select" class="btn-group" data-toggle="buttons">
                                    <label class="btn btn-default<?php if ($update['enable'] == 0) echo ' active'; ?>"
                                           data-toggle-class="btn-primary"
                                           data-toggle-passive-class="btn-default">
                                        <input type="radio" name="enable"
                                               value="0"<?php if ($update['enable'] == 0) echo ' checked="checked"'; ?>>
                                        &nbsp;
                                        No &nbsp;
                                    </label>
                                    <label class="btn btn-default<?php if ($update['enable'] == 1) echo ' active'; ?>"
                                           data-toggle-class="btn-primary"
                                           data-toggle-passive-class="btn-default">
                                        <input type="radio" name="enable"
                                               value="1"<?php if ($update['enable'] == 1) echo ' checked="checked"'; ?>>
                                        &nbsp;
                                        Yes &nbsp;
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Path
                                <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input class="form-control" type="text" name="magento_trigger_path"
                                       value="<?= $update['magento_trigger_path'] ?>"/>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Secret key

                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input class="form-control" type="text" name="magento_trigger_key"
                                       value="<?= $update['magento_trigger_key'] ?>"/>
                            </div>
                        </div>
                        <div class="clearfix"></div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Delete products

                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <div id="delete_trigger" class="btn-group" data-toggle="buttons">
                                    <label class="btn btn-default<?php if ($update['delete_trigger'] == 0) echo ' active'; ?>"
                                           data-toggle-class="btn-primary"
                                           data-toggle-passive-class="btn-default">
                                        <input type="radio" name="delete_trigger"
                                               value="0"<?php if ($update['delete_trigger'] == 0) echo ' checked="checked"'; ?>>
                                        &nbsp;
                                        No &nbsp;
                                    </label>
                                    <label class="btn btn-default<?php if ($update['delete_trigger'] == 1) echo ' active'; ?>"
                                           data-toggle-class="btn-primary"
                                           data-toggle-passive-class="btn-default">
                                        <input type="radio" name="delete_trigger"
                                               value="1"<?php if ($update['delete_trigger'] == 1) echo ' checked="checked"'; ?>>
                                        &nbsp;
                                        Yes &nbsp;
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Create products

                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <div id="create_trigger" class="btn-group" data-toggle="buttons">
                                    <label class="btn btn-default<?php if ($update['create_trigger'] == 0) echo ' active'; ?>"
                                           data-toggle-class="btn-primary"
                                           data-toggle-passive-class="btn-default">
                                        <input type="radio" name="create_trigger"
                                               value="0"<?php if ($update['create_trigger'] == 0) echo ' checked="checked"'; ?>>
                                        &nbsp;
                                        No &nbsp;
                                    </label>
                                    <label class="btn btn-default<?php if ($update['create_trigger'] == 1) echo ' active'; ?>"
                                           data-toggle-class="btn-primary"
                                           data-toggle-passive-class="btn-default">
                                        <input type="radio" name="create_trigger"
                                               value="1"<?php if ($update['create_trigger'] == 1) echo ' checked="checked"'; ?>>
                                        &nbsp;
                                        Yes &nbsp;
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" data-toggle="tooltip"
                                   data-placement="right"
                                   data-original-title="Send images data to Magento">Send images

                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <div id="send_images" class="btn-group" data-toggle="buttons">
                                    <label class="btn btn-default<?php if ($update['send_images'] == 0) echo ' active'; ?>"
                                           data-toggle-class="btn-primary"
                                           data-toggle-passive-class="btn-default">
                                        <input type="radio" name="send_images"
                                               value="0"<?php if ($update['send_images'] == 0) echo ' checked="checked"'; ?>>
                                        &nbsp;
                                        No &nbsp;
                                    </label>
                                    <label class="btn btn-default<?php if ($update['send_images'] == 1) echo ' active'; ?>"
                                           data-toggle-class="btn-primary"
                                           data-toggle-passive-class="btn-default">
                                        <input type="radio" name="send_images"
                                               value="1"<?php if ($update['send_images'] == 1) echo ' checked="checked"'; ?>>
                                        &nbsp;
                                        Yes &nbsp;
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Check description

                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <div id="check_description" class="btn-group" data-toggle="buttons">
                                    <label class="btn btn-default<?php if ($update['check_description'] == 0) echo ' active'; ?>"
                                           data-toggle-class="btn-primary"
                                           data-toggle-passive-class="btn-default">
                                        <input type="radio" name="check_description"
                                               value="0"<?php if ($update['check_description'] == 0) echo ' checked="checked"'; ?>>
                                        &nbsp;
                                        No &nbsp;
                                    </label>
                                    <label class="btn btn-default<?php if ($update['check_description'] == 1) echo ' active'; ?>"
                                           data-toggle-class="btn-primary"
                                           data-toggle-passive-class="btn-default">
                                        <input type="radio" name="check_description"
                                               value="1"<?php if ($update['check_description'] == 1) echo ' checked="checked"'; ?>>
                                        &nbsp;
                                        Yes &nbsp;
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>

                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <button type="submit" name="submit" value="1" class="btn btn-default">
                                    Submit
                                </button>&nbsp;
                                <a href="<?= $this->url('magento', ['action' => 'list']) ?>"
                                   class="btn btn-default" title="Delete the item"> Reset </a>

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>