<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var array $this ->filter
 */

$colspan = 8;
$h = new Parser\Model\Helper\Helper();
$columns = [
    'item_id' => [
        'title' => 'Id',
        'attributes' => ['width' => '3%', 'id' => 'row_item_id', 'data-row' => 'l.parser_magento_log_id'],
        'item_attribute' => '',
    ],
    'type' => [
        'title' => 'Type',
        'attributes' => ['width' => '5%', 'id' => 'row_type', 'data-row' => 'type'],
        'item_attribute' => '',
    ],
    'action' => [
        'title' => 'Action',
        'attributes' => ['width' => '3%', 'id' => 'row_action', 'data-row' => 'l.action'],
        'item_attribute' => '',
    ],
    'magento' => [
        'title' => 'Magento',
        'attributes' => ['id' => 'row_magento', 'data-row' => 'l.store_id'],
        'item_attribute' => '',
    ],
    'title' => [
        'title' => 'Product',
        'attributes' => [],
        'item_attribute' => '',
    ],
    'message' => [
        'title' => 'Message',
        'attributes' => [],
        'item_attribute' => '',
    ],
    'created' => [
        'title' => 'Created',
        'attributes' => ['id' => 'row_created', 'data-row' => 'l.created'],
        'item_attribute' => '',
    ],
    'description' => [
        'title' => 'Description',
        'attributes' => [],
        'item_attribute' => '',
    ],
];
$columnToFilter = [
    'item_id' => '',
    'type' => $this->typeList,
    'action' => $this->actionList,
    'magento' => $this->magentoList,
    'title' => 'Title:<br><input type="text" name="filter[p.title]" value="' . $this->filter['p.title'] . '" class="col-lg-12 form-control w100"/>asin:<br/><input type="text" name="filter[p.asin]" value="' . $this->filter['p.asin'] . '" class="col-lg-12 form-control w100"/>',
    'message' => '',
    'created' => '<div class="input-group date marg-top" id="fromDate"><input type="text" class="from-to fontsmall" style="width:109px;" name="filter[fromCreated]" value="' . $this->filter['fromCreated'] . '"/><span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span></span></div><br/><div class="input-group date" id="toDate"><input type="text" class="from-to fontsmall" style="width:109px;" name="filter[toCreated]" value="' . $this->filter['toCreated'] . '"/><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div>',
    'description' => '<input type="submit" value="Filter" class="btn bg-red-c filter padd-top"/><br/>
                                                <input class="btn btn-default" type="button" value="Reset"
                                                       onclick="window.location = \''
        . $this->url('magento', ['action' => 'showLog'], ['query' => ['resetFilter' => 1]]) .
        '\'"/>',
];
// data column has to be updated manually
?>
<div class="">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <form name="action-form" id="action-form" action="<?= $this->url('magento',
                ['action' => 'showLog'],
                true) ?>" method="post">
                <div class="x_panel">
                    <div class="x_content products-table">
                        <div id="datatable-responsive_wrapper"
                             class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                            <?= $this->paging ?>
                            <div class="row row-top">
                                <div class="col-md-12 col-sm-12 col-xs-12 bulc-actions-select">
                                    <label>Show <?= $this->perPageSelect ?> entries</label>
                                </div>
                            </div>
                            <div class="row scroll">
                                <div class="col-md-12 col-sm-12 col-xs-12 inner-scroll">
                                    <table
                                            class="table table-striped jambo_table bulk_action dataTable products"
                                            role="grid" style="width: 100%;"
                                            width="100%"
                                            cellspacing="0">
                                        <thead>
                                        <tr role="row">
                                            <?php foreach ($columns as $key => $column) : ?>
                                                <th class="column-title"
                                                <?php foreach ($column['attributes'] as $attID => $attVal) : ?>
                                                    <?= " " ?><?= $attID ?>="<?= $attVal ?>"<?= " " ?>
                                                <?php endforeach; ?>
                                                ><?= $column['title'] ?></th>
                                            <?php endforeach; ?>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <?php foreach ($columns as $key => $column) : ?>
                                                <td>
                                                    <?= $columnToFilter[$key] ?>
                                                </td>
                                            <?php endforeach; ?>
                                        </tr>
                                        <?php
                                        if (isset($this->productList) && count($this->productList)) : ?>
                                            <?php foreach ($this->productList as $odd => $product) : ?>
                                                <tr role="row" class="<?php echo ($odd % 2) ? 'odd' : 'even'; ?>">

                                                    <td><?= $product['parser_magento_log_id'] ?></td>
                                                    <td><?php if ($product['error']) : ?>
                                                            <p class="parsley-error">error</p>
                                                        <?php else : ?>
                                                            <p class="parsley-success">message</p>
                                                        <?php endif; ?>
                                                    </td>
                                                    <td class="group">
                                                        <?= $this->actionListForItems[$product['action']] ?>
                                                    </td>
                                                    <td class="product-name">
                                                        <div class="product-name-text"
                                                             title="<?= $product['magento'] ?>">
                                                            <?= $product['magento'] ?>
                                                        </div>
                                                    </td>
                                                    <td class="product-name">
                                                        <div class="product-name-text"
                                                             title="<?= $product['title'] ?>">
                                                            <?= $product['title'] ?><br/>
                                                            <?= $product['asin'] ?>
                                                        </div>
                                                    </td>
                                                    <td class="product-name">
                                                        <div class="product-name-text">
                                                            <?= $product['message'] ?>
                                                            <?= $product['error'] ?>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <?= $this->timeAgo->inWords($product['created']) ?>
                                                    </td>
                                                    <td>
                                                        <div class="product-name-text">
                                                            <?php if ($product['description']) : ?>
                                                                <a data-toggle="modal"
                                                                   data-target=".product-details-<?= $product['parser_magento_log_id'] ?>"
                                                                   class="btn btn-default"
                                                                   title="Click to view detailed info">Details</a>
                                                            <?php endif; ?>
                                                        </div>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        <?php else : ?>
                                            <tr role="row" class="odd">
                                                <td colspan="<?= $colspan ?>" align="center" style="height:300px">
                                                    <strong>No logs found</strong>
                                                </td>
                                            </tr>
                                        <?php endif; ?>
                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <input type="hidden" name="filter[page]" id="product-page" value="<?= $this->filter['page'] ?>"/>
                <input type="hidden" name="product_id" id="product_id" value=""/>
                <input type="hidden" name="check_all" id="check_all" value=""/>
                <input type="hidden" name="filter[sort_column]" id="sort_column"
                       value="<?= $this->filter['sort_column'] ?>"/>
                <input type="hidden" name="filter[sort_type]" id="sort_type" value="<?= $this->filter['sort_type'] ?>"/>
            </form>

        </div>
    </div><!-- row -->
</div><!-- '' -->
<?php if (isset($this->productList) && count($this->productList)) : ?>
    <?php foreach ($this->productList as $odd => $product) :
        if ($product['description']) :
            ?>
            <div class="modal fade bs-example-modal-lg product-details-<?= $product['parser_magento_log_id'] ?>"
                 tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">

                        <div class="modal-header">
                            <button type="button" class="close"
                                    data-dismiss="modal"><span
                                        aria-hidden="true">×</span>
                            </button>
                            <h4 class="modal-title">Description</h4>
                        </div>
                        <div class="modal-body">
                            <div><?= $product['description'] ?>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default"
                                    data-dismiss="modal">Close
                            </button>
                        </div>

                    </div>
                </div>

                <div class="tooltiptext1" style="display: none">
                </div>
            </div>
        <?php
        endif;
    endforeach; ?>
<?php endif; ?>


<script>
    $('#fromDate').datetimepicker({
        format: 'DD/MM/YY HH:mm'
    });
    $('#toDate').datetimepicker({
        format: 'DD/MM/YY HH:mm'
    });
    $('#select-all').click(function (event) {
        $('.product-checkbox-selector').each(function () {

            this.checked = 'checked';
        });
        $('#check_all').val(1);
    });
    $('.download-csv').click(function () {
        let selected = false;
        $('.product-checkbox-selector').each(function () {
            console.log(this.checked);
            if (this.checked) selected = true;
        });
        if (selected === true) {
            var csvType = $(this).attr('data');
            $("#download_csv").val(csvType);
            $("#action-form").attr("target", "_blank");
            $("#action-form").submit();
        } else {
            // do notification
            new PNotify({
                title: 'No items selected',
                text: 'Please choose some items.',
                styling: 'bootstrap3'
            });
        }
        $("#download_csv").val("");
        $("#action-form").attr("target", "_self");
    });
    $('#unselect-all').click(function (event) {
        $('.product-checkbox-selector').each(function () {
            this.checked = '';
        });
        $('#check_all').val('');
    });

    $('#select-visible').click(function (event) {
        $('.product-checkbox-selector').each(function () {
            this.checked = 'checked';
        });
    });
    $('#unselect-visible').click(function (event) {
        $('.product-checkbox-selector').each(function () {
            this.checked = '';
        });
    });


    $('#mass-action-submit').click(function (event) {
        $('#action-form').submit();
    });
    $('#btn-mass-update-action').click(function (event) {
        $('#action-form').submit();
    });


    $('#per-page').change(function (event) {
        $('#action-form').submit();
    });

    function changePage(page) {
        $('#product-page').val(page);
        $('#action-form').submit();
    }

    $('#close-popup-link').click(function (event) {
            $('#popup').hide();
        }
    );

    $(function () {
        $(".column-title").each(function () {
            let attributeValue = $(this).attr('data-row');
            let classValue = "sorting";
            let currentSortColumn = $('#sort_column').val();
            let currentSortType = $('#sort_type').val();

            if (attributeValue) {
                if (attributeValue == currentSortColumn) {
                    classValue = currentSortType == 'asc' ? 'sorting_asc' : 'sorting_desc';
                }
                $(this).addClass(classValue);
                //console.log(classValue + " " + attributeValue);
            }
        });
    });
    $(".column-title").click(function (event) {
        if (event.target.id) {
            let element = $('#' + event.target.id);
            let currentSortColumn = $('#sort_column').val();
            let currentSortType = $('#sort_type').val();
            let type = 'desc';
            if (element.attr('data-row') === currentSortColumn) {
                type = currentSortType === 'asc' ? 'desc' : 'asc';
                $('#sort_type').val(type);
            } else {
                $('#sort_type').val(type);
                $('#sort_column').val(element.attr('data-row'));
            }
            $('#action-form').submit();
        }
    });
    $(".js-switch").change(function (event) {
        if (event.target.id) {
            let element = $('#' + event.target.id);
            let elementToChange = $('#' + element.attr('data-row'));
            if (elementToChange) {
                if (element.is(':checked')) {
                    elementToChange.val('1');
                } else {
                    elementToChange.val('0');
                }
            }
        }
    })

</script>

