<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$demo  = $this->asset('demo');
?>
<div class="nav_menu">
    <nav>
        <div class="nav toggle"><a id="menu_toggle"><i class="fa fa-bars"></i></a></div>

        <ul class="nav navbar-nav navbar-right">

            <?php if($demo) : ?>
                <li><a href="https://web-experiment.info/amazon-parser" target="_blank" class="btn bg-red">Buy now</a>
                </li>
            <?php endif; ?>
            <?php if($this->identity) : ?>
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                       aria-expanded="false">
                        Hello, <?= $this->identity ?> <i class="fa  fa-smile-o"></i>
                    </a>

                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="<?= $this->url('profile', ['action' => 'edit']) ?>"> Profile</a></li>
                        <li><a href="<?= $this->url('profile', ['action' => 'logout']) ?>">
                                <i class="fa fa-sign-out pull-right"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            <?php else: ?>
                <li class="">
                    <a href="<?= $this->url('profile', ['action' => 'login']) ?>" class="user-profile">
                        Login
                    </a>
                </li>
            <?php endif; ?>

        </ul>
    </nav>
</div>
