<?php
/* @var $form  Cdiscount\Model\Form\SearchForm */
?>

<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>

<div class="">
    <div class="page-title">
        <div class="title_center">
            <h1>Add Cdiscount category</h1>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <?php
            $syncStatuses = \Parser\Model\Configuration\ProductSyncable::getOptions();
            $syncStatus = $syncStatuses[\Parser\Model\Configuration\ProductSyncable::SYNCABLE_PRESYNCED];
            ?>
            <div class="x_panel">
                <div class="x_content">
                    <?php $categoryElement = $form->get('category_url'); ?>
                    <?php if($this->message) : ?>
                        <div class="alert alert-info alert-dismissible" role="alert"><strong>
                                <?= $this->message ?>
                            </strong></div>
                    <?php endif; ?>
                    <?php if($this->errors) : ?>
                        <div class="alert alert-danger alert-dismissible" role="alert"><strong>
                                <?= $this->errors ?>
                            </strong></div>
                    <?php endif; ?>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Select sync status
                            <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <div id="syncable-select" class="btn-group" data-toggle="buttons">
                                <?php foreach($syncableList as $syncableItem => $value) : ?>
                                    <label class="btn btn-default<?php if($syncable == $syncableItem) echo ' active'; ?>"
                                           data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                        <input type="radio" name="syncable"
                                               value="<?= $syncableItem ?>"<?php if($syncable == $syncableItem) echo ' checked="checked"'; ?>>
                                        &nbsp; <?= $value ?> &nbsp;
                                    </label>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                    <?php if(count($storeList)) : ?>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Choose magento stores
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <div id="syncable-select" class="btn-group" data-toggle="buttons">
                                <?php foreach($storeList as $id => $store) : ?>
                                    <label class="btn btn-default<?php if($store['selected']) echo ' active'; ?>"
                                           data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                        <input type="checkbox" name="magentoStore[<?= $id ?>]"
                                               value="<?= $id ?>"<?php if($store['selected']) echo ' checked="checked"'; ?>>
                                        &nbsp; <?= $store['title'] ?> &nbsp;
                                    </label>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                    <?php endif;?>

                    <!--div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Auto paging
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <div id="autopaging-select" class="" data-toggle="">
                                <label>
                                    <input type="checkbox"  name="autoPaging" value="1" class="js-switch" <?php if($autoPaging) echo ' checked'; ?> />
                                </label>
                            </div>
                        </div>
                    </div-->
<?php /* ?>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Scrape sub categories
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <div id="autoScrapeCategories-select" class="" data-toggle="">
                                <label>
                                    <input type="checkbox"  name="autoScrapeCategories" value="1" class="js-switch" <?php if($autoScrapeCategories) echo ' checked'; ?> />
                                </label>
                            </div>
                        </div>
                    </div>
 <?php */ ?>
                    <?php
                    foreach ($form->getElements() as $customElement) {
                        if ($customElement->getAttribute('data') === 'custom') {
                            ?>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12"><?php echo $this->formLabel($customElement); ?>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <?php echo $this->formText($customElement); ?>
                                </div>
                            </div>
                            <?php
                        }
                    }
                    ?>
                    <div class="clearfix"></div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12"><?php echo $this->formLabel($categoryElement); ?>
                            <span class="required">*</span> </label>
                        <div class="col-md-6 col-sm-6 col-xs-12"> <?php echo $this->formTextarea($categoryElement); ?>
                            <?php if($this->formElementErrors($categoryElement)) : ?>
                                <ul class="parsley-errors-list filled" id="parsley-id-2">
                                    <li class="parsley-required">
                                        <?= $this->formElementErrors($categoryElement) ?>
                                    </li>
                                </ul>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php $fileElement = $form->get('category_list'); ?>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" data-toggle="tooltip"
                               data-placement="right" title=""
                               data-original-title="File format per line: Marketplace Category;Marketplace Category Name;Web Hierarchy Location Codes;Category Url
"><?php echo $this->formLabel($fileElement); ?> <br> Download <a href="<?= $this->url('crawler', ['action' => 'sampleFileCategoryList']) ?>">sample file</a>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php echo $this->formFile($fileElement); ?>
                            <?php if ($this->formElementErrors($fileElement)) : ?>
                                <ul class="parsley-errors-list filled" id="parsley-id-1">
                                    <li class=""><?= $this->formElementErrors($fileElement) ?></li>
                                </ul>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button type="submit" class="btn btn-default">Submit</button>
                        </div>
                    </div>

                </div>
                <!-- x_content -->
            </div>
            <!--div class="row scroll">
                <div class="col-md-12 col-sm-12 col-xs-12 inner-scroll">
                    <?php
//                    echo $this->table;
                    ?>
                </div>
            </div-->
            <!-- x_panel-->
        </div>
    </div>
</div>

<!-- x_panel -->
</div>
<!-- col-md-4-->
<?php echo $this->form()->closeTag(); ?>
						
						
						 
                  
