<div class="page-title">
    <div class="title_center">
        <h1>Quick-start Guide</h1>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h1></h1>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="col-md-3 col-sm-12 col-xs-12 form-group">

                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <p>This tutorial video is designed to help you in understanding about Data Extraction Engine
                        principles and opportunities - in just 5 minutes. You will learn how to upload products to sync
                        with Amazon, how to manage results, and export data to CSV, as well as how to check key
                        performance indicators.</p>
                    <style>
                        .videowrapper {
                            float: none;
                            clear: both;
                            width: 100%;
                            position: relative;
                            padding-bottom: 56.25%;
                            padding-top: 25px;
                            height: 0;
                        }

                        .videowrapper iframe {
                            position: absolute;
                            top: 0;
                            left: 0;
                            width: 100%;
                            height: 100%;
                        }

                    </style>
                    <div class="videowrapper">
                        <iframe src="https://www.youtube.com/embed/LB1E9plc0a8?rel=0&amp;showinfo=0" frameborder="0"
                                allowfullscreen=""></iframe>
                    </div>
                    <p class="sem">*Synthesized Speech: Amazon Polly</p>
                </div>
                <div class="col-md-3 col-sm-12 col-xs-12 form-group">

                </div>
            </div><!--x_content-->
        </div><!-- x_panel -->
    </div><!-- col-md-12 -->
</div>